// The short talks Kofi reads out inside the houses. Every line is drawn from understand-veganism.com:
// the page each house opens. Keep them under about 160 words so a talk stays around a minute.
export const TALK_VOICE = "Kofi";
export const TALKS = {
  definition: { title: "What is veganism?", page: "definition/", text:
    "Veganism is the principle that animals are not ours to use. It rejects the idea that animals exist for human purposes, as property, resources or commodities, and recognises them as someone, not something. It was defined in 1951 as the doctrine that man should live without exploiting animals. It was never a diet, an environmental strategy or a health programme, and not a campaign for less suffering. Because it rests on a principle, it needs no list of permitted and forbidden things. Think of any principle you already hold. If what belongs to other people is not yours to take, you do not carry an inventory of every object you must not steal. When a situation arises, you apply the principle. It is the same with veganism. Practices may change as circumstances do. The principle does not." },
  welfare: { title: "The welfare trap", page: "welfare/", text:
    "Welfare reform asks one question: how should we treat animals while we use them? Veganism asks a different one: do we have any right to use them at all? These are not two steps on the same road. They point in opposite directions. A cage-free label does not tell you to stop exploiting animals. It tells you that exploiting animals is fine. That is the trap. Every successful reform teaches the public that the use was never the problem, only the conditions. And the organisations paid to fix the conditions are the same ones that need the use to continue. Welfare organisations raise donations from people who believe the problem is being solved, and animal-use industries pay them for certifications and moral cover. Two hundred years of welfare reform have run alongside the greatest expansion of animal use in history. The wrong to address is use. Not how." },
  symptoms: { title: "The symptoms", page: "symptoms/", text:
    "The suffering you see in footage of animal use is real, and it is standard practice across the world. But it is a symptom, not the root. Much animal use produces no obvious suffering at all: backyard eggs, wool from sheep who graze happily, hand-milked goats, working dogs. The root injustice in all of them is the same: treating sentient beings as resources to be used. Veganism opposes that. Not because of how animals are treated, but because they are used at all. The root cause is the belief that animals exist for us to use. When that belief is rejected, the symptoms collapse with it. Veganism does not seek to reform these practices or make them more humane. It seeks to end the use of animals entirely." },
  "a-vegan-world": { title: "A vegan world", page: "a-vegan-world/", text:
    "A vegan world begins with one shift, not a thousand fixes. Animals stop being property, morally and legally. That is the whole change. The end of factory farming, the end of the slaughterhouse, the end of the testing lab: these are not separate goals. They are downstream effects of that one foundational shift. Welfarism works the opposite way. It treats every cruelty as its own problem to be managed, a bigger cage here, a humane stun there, and the work never ends, because the status of animals as things we own and use is left untouched. Let us be honest about the limits. A vegan world does not end all suffering. Animals will still die in the wild. What ends is regarding animals as ours to use, whether on an industrial scale or in a single back garden. This is not idealism. It is just the logic." },
  "lab-flesh": { title: "Lab flesh", page: "lab-flesh/", text:
    "Is lab flesh vegan? No. Lab flesh reinforces the idea that animals exist for us to use. It does not challenge anyone to end using them. Its goal is to reduce suffering in one form of use, which is a welfare position, not a vegan one. Veganism rejects animal use regardless of whether the use is painful. Notice what lab flesh does not touch. Not zoos. Not horse racing. Not vivisection. Not riding. Not wool. It is not a stance against use. It is a stance against suffering inside one industry. The category flesh stays on the table. The animal stays a resource. The mindset stays exactly as it was. The only thing that changes is the equipment. As Leslie Cross wrote in 1951, veganism is a principle, that man has no right to exploit the creatures for his own ends, and no variation occurs." },
  "dogmatic-vegan": { title: "The dogmatic vegan", page: "dogmatic-vegan/", text:
    "If you hold the original line, that animals are not ours to use, you notice something strange. The pushback rarely comes from outsiders. It comes from inside the movement, from people who call themselves vegan but treat it as harm reduction. And you get the labels: purist, extremist, dogmatic, divisive. This is not new. In every justice movement in history, the people demanding real change were told they were too extreme, and the sharpest attacks came from the moderates on their own side. There are two incompatible ideas of veganism. One is a line: humans have no right to exploit animals, regardless of suffering. The other is a dial: anything that lowers the total suffering counts as a win. Purist only stings if being uncompromising about an injustice is a fault. No one wants an abolitionist who was flexible about slavery." },
  sic: { title: "Single-issue campaigns", page: "sic/", text:
    "Forty years of bans, boycotts and celebrity campaigns, and animal use by humans has only increased. A single-issue campaign targets one form of animal use, fur, veal, foie gras, circuses, and asks the public to oppose that one thing. The principle that animals exist for human use is left untouched. So the industry pivots, the use continues, and the public walks away feeling absolved. Take fur. Over forty years of campaigns, more than twenty countries banned fur farming, and the number of industries that stopped using animals as a result is zero. Brands dropped fur and picked up cow skin, sheep wool and exotic skins instead. The UK banned veal crates in 1990, and the result was rose veal: same industry, same calves killed, new welfare branding. You cannot say animals are not ours to use and then campaign for just not like this. Veganism is the baseline, not the destination." },
  timeline: { title: "How the definition was diluted", page: "timeline/", text:
    "Veganism was defined by Leslie Cross in 1951 as the doctrine that man should live without exploiting animals. The founders never redefined it. Everything that followed was distortion. In 1957 the definition disappeared from the Society's constitution. In the sixties the movement was recentred from the animal to the practitioner: lifestyle, health, environmental stewardship. The victim disappeared. In 1975 Peter Singer replaced exploitation with suffering as the moral threshold, so use became acceptable if painless. Then, in 1979, came the fatal redefinition, with three insertions: as far as is possible and practicable, the escape clause; cruelty to, alongside exploitation; and the benefit of humans, animals and the environment. By 2010 the plant-based rebrand had removed the ethical content altogether. The animals were the only reason the word existed. The founders never redefined it. You are here to fix it." },
  lesliecross: { title: "Leslie Cross: the letters", page: "lesliecross/", text:
    "Until 1951, veganism had no clear formal definition. Leslie Cross was the person who set out to define what veganism actually meant, and wrote the letters that gave it one. He and others spent years working on the wording, carefully guarding the principle from drifting into the language of welfare or reducing harm. They knew that once a definition was loose, the meaning would slip with it. In 1951 the Vegan Society's object became to end the exploitation of animals by man, and the word veganism came to mean the doctrine that man should live without exploiting animals. Not so much welfare, Cross wrote, as liberation, because the relationship is in the main one of master and slave, and it has to be abolished before something better and finer can be built." },
  quotes: { title: "Leslie Cross, in his own words", page: "quotes/", text:
    "Here is veganism in Leslie Cross's own words, from the founding letters he wrote for The Vegan between 1949 and 1955. In 1949: the principle of the emancipation of animals from exploitation by man. In 1951: the object of the Society shall be to end the exploitation of animals by man, and the word veganism shall mean the doctrine that man should live without exploiting animals. And in 1955: this principle, this doctrine, is concerned with one matter only. A big matter, it is true, but a clearly defined one: the matter of the right relationship between man and the animals. Veganism is itself a principle, from which certain practices naturally flow. But it is in itself a principle, and not a set of practices." },
  explainers: { title: "Use, not killing", page: "explainers/", text:
    "Here is something most people miss. Veganism is not about not killing animals. It is about not using them. You can exploit animals without killing them: taking eggs from hens, riding horses, shearing sheep for wool, using animals for entertainment. All of these are exploitation, even if the animal is not killed. And you can kill animals without exploiting them: a deer hit by a car, or a mouse dying in a crop harvest, is not use. If veganism were just about not killing, then using animals for labour, taking their eggs or riding them would be acceptable. It is not, because they are still being used. The key question is always the same: are you using this animal as a resource for your benefit? If yes, that is exploitation, and that is what veganism opposes." },
};
